
/*  © Copyright CERN, 2015. All rights not expressly granted are reserved.
        
    The stub of this file was generated by Quasar (additional info: using transform designToDeviceHeader.xslt) 
    on 2020-03-04T17:40:17.039Z
    
    Quasar is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public Licence as published by
    the Free Software Foundation, either version 3 of the Licence.
    Quasar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public Licence for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Quasar.  If not, see <http://www.gnu.org/licenses/>.
    
    
    
 */





#ifndef __DPurityMonitor__H__
#define __DPurityMonitor__H__

#include <vector>
#include <boost/thread/mutex.hpp>

#include <statuscode.h>
#include <uadatetime.h>
#include <session.h>


#include <DRoot.h>
#include <Configuration.hxx>

#include <Base_DPurityMonitor.h>


namespace Device
{




  class DPurityMonitor:public Base_DPurityMonitor
  {

  public:
    /* sample constructor */
    explicit DPurityMonitor (const Configuration::PurityMonitor & config,
			     Parent_DPurityMonitor * parent);
    /* sample dtr */
     ~DPurityMonitor ();




    /* delegators for
       cachevariables and sourcevariables */

    /* Note: never directly call this function. */


    UaStatus writeRunningConfiguration (const OpcUa_Int16 & v);

    /* Note: never directly call this function. */


    UaStatus writeTakeData (const OpcUa_Int16 & v);

    /* Note: never directly call this function. */


    UaStatus writeDoAnalysis (const OpcUa_Int16 & v);


    /* delegators for methods */


  private:
    /* Delete copy constructor and assignment operator */
      DPurityMonitor (const DPurityMonitor &);
      DPurityMonitor & operator= (const DPurityMonitor & other);

    // ----------------------------------------------------------------------- *
    // -     CUSTOM CODE STARTS BELOW THIS COMMENT.                            *
    // -     Don't change this comment, otherwise merge tool may be troubled.  *
    // ----------------------------------------------------------------------- *

  public:

      void update();
      UaString executeCommand(char *cmd);

  private:


  };





}

#endif // include guard
